version: '2.3'
services:
  spring:
    image: mariemnajjar/projetdevops
    ports:
      - "8089:8089"
    depends_on:
      - dbmysql

  dbmysql:
    image: "mysql:5.6"
    container_name: my-dbmysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
volumes:
  db: